/**
 * This file is automatically generated by make.
 * All changes will be overrided next time you compile
**/
#pragma once
#include <iostream>
#include <vector>
#include <string>

#include <../inc/scenes/Game.hpp>
#include <../inc/scenes/Menu.hpp>

using namespace std;

std::vector<pair<string, Scene*>> scenes;

extern void import_scenes() {
	scenes.emplace_back("Game", new Game());
	scenes.emplace_back("Menu", new Menu());
}
